providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev --no-audit --prefer-offline"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
